"""
Turkce UI stringleri.

Kullaniciya gorunen metinler bu dosyada toplanir.
"""

# Uygulama
APP_TITLE = "Elektronik Harp Arayuz Sistemi"
APP_VERSION = "v0.1.0"
APP_FULL_TITLE = f"{APP_TITLE} - {APP_VERSION}"
WINDOW_TITLE_PROJECT = "{app_title} - {name}"
APP_ORGANIZATION = "TEKNOFEST"
COMMON_PLACEHOLDER = "-"

# Menu
MENU_FILE = "Dosya"
MENU_FILE_NEW = "Yeni Proje"
MENU_FILE_OPEN = "Proje Ac..."
MENU_FILE_SAVE = "Kaydet"
MENU_FILE_SAVE_AS = "Farkli Kaydet..."
MENU_FILE_EXIT = "Cikis"
MENU_EDIT = "Duzenle"
MENU_VIEW = "Gorunum"
MENU_VIEW_LAYOUT = "Yerlesim"
MENU_RECIPES = "Hazir Akislar"
MENU_HELP = "Yardim"
MENU_HELP_ABOUT = "Hakkinda"

# Toolbar
TOOLBAR_CONTROL = "Kontrol"
TOOLBAR_RUN = "Baslat"
TOOLBAR_STOP = "Durdur"
TOOLBAR_RESET = "Sifirla"
TOOLTIP_RUN = "Uygulamayi calistir"
TOOLTIP_STOP = "Uygulamayi durdur"
TOOLTIP_RESET = "Uygulamayi sifirla"
MODE_DESIGN = "Tasarim"
MODE_OPERATION = "Operasyon"

# Tabs / Dock basliklari
TAB_FLOW_GRAPH = "Akis Grafigi"
TAB_PLOTS = "Grafikler"
PALETTE_TITLE = "Blok Paleti"
PALETTE_SEARCH = "Blok ara..."
PROPERTIES_TITLE = "Ozellikler"
LOG_TITLE = "Terminal"
DOCK_VARIABLES = "Degiskenler"
DOCK_INSPECTOR = "Inceleyici"
DOCK_ISSUES = "Sorunlar"
DOCK_EVENT_FEED = "Olay Akisi"
DOCK_SUMMARY = "Durum Ozeti"
DOCK_SPECTRUM = "Sinyal Spektrumu"
DOCK_WATERFALL = "Selale (Waterfall)"
DOCK_DETECTIONS = "Tespitler Listesi"
SECTION_PIPELINE = "Pipeline Durumu"
SECTION_RUNTIME = "Sistem Sagligi"
SECTION_EVENTS = "Olay ve Hedefler"
NODE_TOOLTIP_INPUTS = "Giris: {value}"
NODE_TOOLTIP_OUTPUTS = "Cikis: {value}"
NODE_TOOLTIP_NONE = "Yok"

# Kategoriler
CAT_SOURCES = "Kaynaklar"
CAT_PROCESSORS = "On Isleme"
CAT_VIEWERS = "Goruntuleyiciler"
CAT_DETECTORS = "Tespit"
CAT_CLASSIFIERS = "Siniflandirma"
CAT_TRACKING = "Izleme"

# Plot etiketleri
PLOT_SPECTRUM = "Spektrum"
PLOT_WATERFALL = "Waterfall"
PLOT_IQ = "IQ / Zaman"
PLOT_DETECTIONS = "Tespitler"
DETECTIONS_HEADER_ID = "ID"
DETECTIONS_HEADER_STATE = "Durum"
DETECTIONS_HEADER_FREQ = "Merkez Frekans (MHz)"
DETECTIONS_HEADER_POWER = "Guc (dB)"
DETECTIONS_HEADER_SNR = "SNR (dB)"
DETECTIONS_HEADER_BW = "BW (kHz)"
DETECTIONS_HEADER_HIT = "Hit"
DETECTIONS_HEADER_LAST_SEEN = "Son Gorulme (s)"
DETECTIONS_HEADER_DURATION = "Sure (s)"
DETECTIONS_SHOW_STALE = "Stale goster"
DETECTIONS_FREEZE = "Dondur"
DETECTIONS_LIVE = "Canli"
DETECTIONS_COUNT_ACTIVE = "{count} aktif"
DETECTIONS_COUNT_ACTIVE_STALE = "{active} aktif  |  {stale} stale"
DETECTIONS_STATE_ACTIVE = "Aktif"
DETECTIONS_STATE_STALE = "Stale"
PLOT_FREQUENCY_LABEL = "Frekans (MHz)"
PLOT_POWER_LABEL = "Guc (dB)"
PLOT_TIME_LABEL = "Zaman (ornek)"
PLOT_AMPLITUDE_LABEL = "Genlik"

# Validation / hata
VALIDATION_ERROR_TITLE = "Dogrulama Hatasi"
VALIDATION_OK = "Sistem gecerli."
ERROR_PIPELINE_EMPTY = "Calistirilacak hicbir blok yok - en az bir blok ekleyin."
ERROR_NO_SOURCE = "Kaynak blogu bulunamadi."
ERROR_PORT_NOT_CONNECTED = "Zorunlu giris portu bagli degil"
ERROR_PORT_INCOMPATIBLE = "Port tipi uyumsuz"
ERROR_CYCLE = "Sistem uzerinde dongu tespit edildi"
WARNING_NO_SINK = "Goruntuleyici blogu yok - cikti gorunmeyecek."

# Durum
STATUS_READY = "Hazir"
STATUS_RUNNING = "Calisiyor..."
STATUS_STOPPED = "Durduruldu"
STATUS_ERROR = "Hata"
STATUS_ISSUES_FOUND = "{count} sorun bulundu"
STATUS_NO_FLOW_TO_SAVE = "Kaydedilecek akis bulunamadi."
STATUS_LAYOUT_APPLIED = "Yerlesim uygulandi: {name}"

# Diyaloglar
DIALOG_UNSAVED = "Kaydedilmemis degisiklikler var. Kaydetmek ister misiniz?"
DIALOG_UNSAVED_TITLE = "Kaydedilmemis Degisiklikler"
DIALOG_ABOUT_TEXT = (
    f"<h3>{APP_TITLE}</h3>"
    f"<p>{APP_VERSION}</p>"
    "<p>SDR tabanli Elektronik Harp Arayuz Sistemi</p>"
    "<p>TEKNOFEST 2026</p>"
)
DIALOG_FILE_FILTER = "EH Proje Dosyasi (*.ehproj);;Tum Dosyalar (*)"
DIALOG_ERROR_TITLE = "Hata"
DIALOG_PROJECT_LOAD_ERROR = "Proje yuklenemedi:\n{error}"
DIALOG_PROJECT_SAVE_ERROR = "Kaydedilemedi:\n{error}"
PROJECTIO_FILE_NOT_FOUND = "Proje dosyasi bulunamadi: {path}"
PROJECTIO_VERSION_UNSUPPORTED = "Desteklenmeyen proje surumu: {version} (beklenen: {expected})"

# Log seviyeleri
LOG_INFO = "[BILGI]"
LOG_WARNING = "[UYARI]"
LOG_ERROR = "[HATA]"
LOG_DEBUG = "[DEBUG]"
LOG_CLEAR = "Temizle"

# Log mesajlari
LOG_APP_STARTED = "{title} baslatildi."
LOG_REGISTERED_BLOCK_COUNT = "Kayitli blok sayisi: {count}"
LOG_GRAPH_LOADED = "Yeni proje yuklendi."
LOG_PROJECT_CREATED = "Yeni proje olusturuldu."
LOG_PROJECT_LOADED = "Proje yuklendi: {path}"
LOG_PROJECT_SAVED = "Proje kaydedildi: {path}"
LOG_RECIPE_READY = "Hazir akis yuklendi: {name}"
LOG_RECIPE_FILE_LOADED = "Akis tarifi yuklendi: {path}"
LOG_RECIPE_FILE_SAVED = "Akis tarifi kaydedildi: {path}"
LOG_RECIPE_FILE_LOAD_ERROR = "Tarif yuklenemedi:\n{error}"
LOG_RECIPE_FILE_SAVE_ERROR = "Tarif kaydedilemedi:\n{error}"
LOG_TARGET_CONFIRMED = (
    "[TESPIT] Hedef #{target_id} Kararli olarak isaretlendi: "
    "{freq_mhz:.3f} MHz | Guc: {power:.1f} dB | SNR: {snr:.1f} dB"
)
LOG_UNKNOWN_NODE_TYPE = "Bilinmeyen blok tipi: {node_type_id}"
LOG_NODE_ADDED = "Blok eklendi: {name}"
LOG_NODE_CONFIG_UPDATED = "Blok ayarlari guncellendi."
LOG_VARIABLES_UPDATED = "Global degiskenler guncellendi."
LOG_PIPELINE_STARTED = "Pipeline baslatildi."
LOG_PIPELINE_STOPPED = "Pipeline durduruldu."
LOG_WORKSPACE_RESET = "Calisma alani sifirlandi."
LOG_PLUGIN_DISCOVERY_SUMMARY = "Plugin kesfi: {loaded} yuklendi, {failed} hata, {count} aday"
LOG_PLUGIN_DISCOVERY_LOADED = "Plugin yuklendi: {name} ({manifest_count} manifest)"
LOG_PLUGIN_DISCOVERY_ERROR = "Plugin hatasi [{name}]: {error}"
ERROR_SYSTEM_RUNTIME = "Sistem hatasi olustu."

# Sag tik menusu
CTX_DELETE = "Sil"
CTX_DUPLICATE = "Cogalt"
CTX_PROPERTIES = "Ozellikler"
CTX_DISCONNECT = "Baglantilari Kes"
CTX_ADD_BLOCK = "Blok Ekle"
CTX_SELECT_ALL = "Tumunu Sec"
CTX_RESET_VIEW = "Gorunumu Sifirla"
CTX_FIT_ALL = "Tumunu Sigdir"

# Recipe
ACTION_RECIPE_SAVE = "Akisi Tarif Olarak Kaydet..."
ACTION_RECIPE_LOAD = "Tarif Dosyasi Yukle..."
RECIPE_DEFAULT_NAME = "Kaydedilen Akis"
RECIPE_STANDARD_DETECTION_NAME = "Standart Tespit Hatti"
RECIPE_STANDARD_DETECTION_DESC = "SigMF -> STFT -> CFAR -> Kararlilik zincirini olusturur."
RECIPE_SPECTRUM_ONLY_NAME = "Spektrum Izleme"
RECIPE_SPECTRUM_ONLY_DESC = "Yalnizca SigMF -> STFT hattini kurar."
DIALOG_RECIPE_OPEN_TITLE = "Tarif Dosyasi Yukle"
DIALOG_RECIPE_SAVE_TITLE = "Akisi Tarif Olarak Kaydet"
DIALOG_RECIPE_FILTER = "EH Akis Tarifi (*.ehrecipe);;Tum Dosyalar (*)"
DIALOG_RECIPE_NAME_TITLE = "Akis Tarifi"
DIALOG_RECIPE_NAME_LABEL = "Tarif adi:"
DIALOG_RECIPE_DESC_TITLE = "Tarif Aciklamasi"
DIALOG_RECIPE_DESC_LABEL = "Kisa aciklama:"
DIALOG_RECIPE_DEFAULT_DESC = "Kaydedilen kullanici akis tarifi."
RECIPEIO_VERSION_UNSUPPORTED = "Desteklenmeyen akis tarifi surumu: {version}"
RECIPEIO_INVALID_UI_MODE = "Gecersiz UI modu: {value}"
RECIPEIO_UNKNOWN_LAYOUT = "Bilinmeyen yerlesim preseti: {value}"
RECIPEIO_EMPTY_FLOW = "Akis tarifi en az bir blok icermelidir."
RECIPEIO_UNKNOWN_NODE_TYPE = "Tarifte bilinmeyen blok tipi kullaniliyor: {value}"
RECIPEIO_INVALID_SOURCE_INDEX = "Gecersiz kaynak blok index'i: {value}"
RECIPEIO_INVALID_TARGET_INDEX = "Gecersiz hedef blok index'i: {value}"
RECIPEIO_SOURCE_PORT_MISSING = "Cikis portu bulunamadi: {value}"
RECIPEIO_TARGET_PORT_MISSING = "Giris portu bulunamadi: {value}"
RECIPEIO_PORT_INCOMPATIBLE = "Tarif icinde uyumsuz port baglantisi: {value}"

# Layout
LAYOUT_PRESET_DESIGN = "Tasarim Yerlesimi"
LAYOUT_PRESET_OPERATION = "Operasyon Yerlesimi"
LAYOUT_PRESET_ANALYSIS = "Analiz Yerlesimi"

# Inspector
INSPECTOR_TITLE = "Inceleyici"
INSPECTOR_APPLY = "Uygula"
INSPECTOR_CLOSE_TOOLTIP = "Paneli kapat"
INSPECTOR_DESCRIPTION_MISSING = "Aciklama bulunmuyor."
INSPECTOR_PORT_NONE = "Yok"
INSPECTOR_PORT_INPUTS = "Girisler: {value}"
INSPECTOR_PORT_OUTPUTS = "Cikislar: {value}"
INSPECTOR_RUNTIME_STATE = "Durum:"
INSPECTOR_RUNTIME_FRAMES = "Islenen Kare:"
INSPECTOR_RUNTIME_DROPS = "Bos Kare:"
INSPECTOR_RUNTIME_LATENCY = "Son Gecikme:"
INSPECTOR_RUNTIME_AVG_LATENCY = "Ort. Gecikme:"
INSPECTOR_RUNTIME_LAST_SEEN = "Son Veri:"
INSPECTOR_RUNTIME_LAST_OUTPUT = "Son Cikis:"
INSPECTOR_RUNTIME_PROBE_HISTORY = "Probe Gecmisi:"
INSPECTOR_RUNTIME_LAST_ERROR = "Son Hata:"
INSPECTOR_FILE_BROWSE = "Gozat..."
INSPECTOR_FILE_PICKER_TITLE = "Dosya Sec"
INSPECTOR_FILE_PICKER_FILTER = "Tum Dosyalar (*)"
INSPECTOR_ELAPSED = "{age:.1f} sn once"
INSPECTOR_STATE_IDLE = "Hazir"
INSPECTOR_STATE_RUNNING = "Calisiyor"
INSPECTOR_STATE_WARNING = "Uyari"
INSPECTOR_STATE_STALE = "Beklemede"
INSPECTOR_STATE_ERROR = "Hata"

# Variables
VARIABLES_HINT = "Degiskenler config alanlarinda ${degisken} veya = ifade seklinde kullanilabilir."
VARIABLES_ADD_ROW = "Satir Ekle"
VARIABLES_REMOVE_ROW = "Seciliyi Sil"
VARIABLES_APPLY = "Degiskenleri Uygula"
VARIABLE_HEADER_NAME = "Ad"
VARIABLE_HEADER_TYPE = "Tur"
VARIABLE_HEADER_VALUE = "Deger"
VARIABLE_TYPE_TEXT = "Metin"
VARIABLE_TYPE_INT = "Tam Sayi"
VARIABLE_TYPE_FLOAT = "Ondalik"
VARIABLE_TYPE_BOOL = "Mantiksal"

# Issues
ISSUES_NONE = "Aktif sorun yok."
ISSUES_NONE_DETAIL = "Sistem su anda bilinen bir hata veya uyari uretmiyor."
ISSUES_SUMMARY = "{errors} hata  |  {warnings} uyari  |  {runtime} calisma  |  {preview} onizleme"
ISSUE_LEVEL_ERROR = "Hata"
ISSUE_LEVEL_WARNING = "Uyari"
ISSUE_SOURCE_RUNTIME = "Calisma Zamani"
ISSUE_SOURCE_VALIDATION = "Baslatma Dogrulamasi"
ISSUE_SOURCE_PREVIEW = "Duzenleme Onizlemesi"
ISSUE_SOURCE_GENERIC = "Dogrulama"
ISSUE_TOOLTIP_NODE = "{message}\nBlok: {node_id}"

# Events
EVENT_LEVEL_INFO = "Bilgi"
EVENT_LEVEL_WARNING = "Uyari"
EVENT_LEVEL_ERROR = "Hata"
EVENT_LEVEL_SUCCESS = "Basarili"
EVENT_LEVEL_DEBUG = "Debug"
EVENT_NONE = "Henuz olay yok."

# Summary
SUMMARY_PIPELINE = "Pipeline:"
SUMMARY_ISSUES = "Sorun:"
SUMMARY_ISSUE_BREAKDOWN = "Sorun Ozeti:"
SUMMARY_ACTIVE_NODES = "Calisan Blok:"
SUMMARY_AVG_LATENCY = "Ort. Gecikme:"
SUMMARY_SLOWEST_NODE = "En Yavas Blok:"
SUMMARY_SOURCE = "Kaynak:"
SUMMARY_VARIABLES = "Degisken:"
SUMMARY_UI_MODE = "Mod:"
SUMMARY_LAYOUT = "Yerlesim:"
SUMMARY_RECIPE = "Akis:"
SUMMARY_PLUGINS = "Plugin:"
SUMMARY_EVENTS = "Olay:"
SUMMARY_LAST_EVENT = "Son Olay:"
SUMMARY_CONFIRMED_TARGETS = "Onayli Hedef:"
SUMMARY_ACTIVE_TRACKS = "Aktif Iz:"
SUMMARY_LAST_TARGET = "Son Hedef:"
SUMMARY_EVENT_BREAKDOWN = "{count} olay / {level}"
SUMMARY_ISSUE_BREAKDOWN_TEXT = "{errors} hata / {warnings} uyari"
SUMMARY_PIPELINE_RUNNING = "Calisiyor"
SUMMARY_PIPELINE_IDLE = "Hazir"
SUMMARY_PIPELINE_ERROR = "Hata"
SUMMARY_SOURCE_NOT_SELECTED = "Dosya secilmedi"
SUMMARY_SOURCE_LOOP = "Dongu"
SUMMARY_SOURCE_SINGLE_PASS = "Tek gecis"
SUMMARY_SOURCE_LABEL = "{name} ({mode})"
SUMMARY_RECIPE_NONE = "Hazir tarif yok"
SUMMARY_RECIPE_CUSTOM = "Ozel akis"
SUMMARY_PLUGIN_NONE = "Plugin yok"
SUMMARY_PLUGIN_STATUS = "{loaded}/{count} yuklu"
SUMMARY_PLUGIN_STATUS_WITH_ERRORS = "{loaded}/{count} yuklu, {failed} hata"

# Edge debug
EDGE_DEBUG_PREVIEW = "Baglanti onizlemesi"
EDGE_DEBUG_SOURCE = "Kaynak: {value}"
EDGE_DEBUG_TARGET = "Hedef: {value}"
EDGE_DEBUG_STATE = "Durum: {value}"
EDGE_DEBUG_TYPE = "Tip: {value}"
EDGE_DEBUG_PAYLOAD = "Yuk: {value}"
EDGE_DEBUG_FRESHNESS = "Tazelik: {value:.0f} ms"
EDGE_DEBUG_WAITING = "Veri bekleniyor"
