"""Türkçe UI metinleri."""

# Uygulama
APP_TITLE = "Elektronik Harp Arayüz Sistemi"
APP_VERSION = "v0.1.0"
APP_FULL_TITLE = f"{APP_TITLE} - {APP_VERSION}"
WINDOW_TITLE_PROJECT = "{app_title} - {name}"
APP_ORGANIZATION = "TEKNOFEST"
COMMON_PLACEHOLDER = "-"

# Menü
MENU_FILE = "Dosya"
MENU_FILE_NEW = "Yeni Proje"
MENU_FILE_OPEN = "Proje Aç..."
MENU_FILE_SAVE = "Kaydet"
MENU_FILE_SAVE_AS = "Farklı Kaydet..."
MENU_FILE_EXIT = "Çıkış"
MENU_EDIT = "Düzenle"
MENU_VIEW = "Görünüm"
MENU_VIEW_LAYOUT = "Yerleşim"
MENU_HELP = "Yardım"
MENU_HELP_ABOUT = "Hakkında"

# Toolbar
TOOLBAR_CONTROL = "Kontrol"
TOOLBAR_RUN = "Başlat"
TOOLBAR_STOP = "Durdur"
TOOLBAR_RESET = "Sıfırla"
TOOLTIP_RUN = "Uygulamayı çalıştır"
TOOLTIP_STOP = "Uygulamayı durdur"
TOOLTIP_RESET = "Çalışma alanını sıfırla"
MODE_DESIGN = "Tasarım"
MODE_OPERATION = "Operasyon"

# Sekmeler / dock başlıkları
TAB_FLOW_GRAPH = "Akış Grafiği"
TAB_PLOTS = "Grafikler"
PALETTE_TITLE = "Blok Paleti"
PALETTE_SEARCH = "Blok ara..."
PROPERTIES_TITLE = "Özellikler"
LOG_TITLE = "Terminal"
DOCK_INSPECTOR = "Detaylar"
DOCK_EVENT_FEED = "Olay Akışı"
DOCK_SUMMARY = "Sistem Özeti"
DOCK_SPECTRUM = "Sinyal Spektrumu"
DOCK_WATERFALL = "Şelale (Waterfall)"
DOCK_DETECTIONS = "Tespit Listesi"
SECTION_PIPELINE = "İşleme Hattı Durumu"
SECTION_RUNTIME = "Sistem Sağlığı"
SECTION_EVENTS = "Olaylar ve Tespitler"
NODE_TOOLTIP_INPUTS = "Giriş: {value}"
NODE_TOOLTIP_OUTPUTS = "Çıkış: {value}"
NODE_TOOLTIP_NONE = "Yok"

# Kategoriler
CAT_SOURCES = "Kaynaklar"
CAT_PROCESSORS = "Ön İşleme"
CAT_VIEWERS = "Görüntüleyiciler"
CAT_DETECTORS = "Tespit"
CAT_CLASSIFIERS = "Sınıflandırma"
CAT_TRACKING = "İzleme"

# Grafik etiketleri
PLOT_SPECTRUM = "Spektrum"
PLOT_WATERFALL = "Waterfall"
PLOT_IQ = "IQ / Zaman"
PLOT_DETECTIONS = "Tespit Edilen Sinyaller"
PLOT_FREQUENCY_LABEL = "Frekans (MHz)"
PLOT_POWER_LABEL = "Güç (dB)"
PLOT_TIME_LABEL = "Zaman (örnek)"
PLOT_AMPLITUDE_LABEL = "Genlik"

DETECTIONS_HEADER_ID = "ID"
DETECTIONS_HEADER_STATE = "Durum"
DETECTIONS_HEADER_FREQ = "Merkez Frekans (MHz)"
DETECTIONS_HEADER_POWER = "Güç (dB)"
DETECTIONS_HEADER_SNR = "SNR (dB)"
DETECTIONS_HEADER_BW = "BW (kHz)"
DETECTIONS_HEADER_HIT = "Hit"
DETECTIONS_HEADER_LAST_SEEN = "Son Görülme (s)"
DETECTIONS_HEADER_DURATION = "Süre (s)"
DETECTIONS_SHOW_STALE = "Eskileri göster"
DETECTIONS_FREEZE = "Dondur"
DETECTIONS_LIVE = "Canlı"
DETECTIONS_COUNT_ACTIVE = "{count} aktif"
DETECTIONS_COUNT_ACTIVE_STALE = "{active} aktif | {stale} eski"
DETECTIONS_STATE_ACTIVE = "Aktif"
DETECTIONS_STATE_STALE = "Eski"

# Doğrulama / hata
VALIDATION_ERROR_TITLE = "Doğrulama Hatası"
VALIDATION_OK = "Sistem geçerli."
ERROR_PIPELINE_EMPTY = "Çalıştırılacak hiçbir blok yok. En az bir blok ekleyin."
ERROR_NO_SOURCE = "Kaynak bloğu bulunamadı."
ERROR_PORT_NOT_CONNECTED = "Zorunlu giriş portu bağlı değil"
ERROR_PORT_INCOMPATIBLE = "Port tipi uyumsuz"
ERROR_CYCLE = "Sistem üzerinde döngü tespit edildi"
WARNING_NO_SINK = "Görüntüleyici bloğu yok. Çıktı görünmeyecek."

# Durum
STATUS_READY = "Hazır"
STATUS_RUNNING = "Çalışıyor..."
STATUS_STOPPED = "Durduruldu"
STATUS_ERROR = "Hata"
STATUS_ISSUES_FOUND = "{count} sorun bulundu"
STATUS_NO_FLOW_TO_SAVE = "Kaydedilecek akış bulunamadı."
STATUS_LAYOUT_APPLIED = "Yerleşim uygulandı: {name}"

# Diyaloglar
DIALOG_UNSAVED = "Kaydedilmemiş değişiklikler var. Kaydetmek ister misiniz?"
DIALOG_UNSAVED_TITLE = "Kaydedilmemiş Değişiklikler"
DIALOG_ABOUT_TEXT = (
    f"<h3>{APP_TITLE}</h3>"
    f"<p>{APP_VERSION}</p>"
    "<p>SDR tabanlı Elektronik Harp Arayüz Sistemi</p>"
    "<p>TEKNOFEST 2026</p>"
)
DIALOG_FILE_FILTER = "EH Proje Dosyası (*.ehproj);;Tüm Dosyalar (*)"
DIALOG_ERROR_TITLE = "Hata"
DIALOG_PROJECT_LOAD_ERROR = "Proje yüklenemedi:\n{error}"
DIALOG_PROJECT_SAVE_ERROR = "Kaydedilemedi:\n{error}"
PROJECTIO_FILE_NOT_FOUND = "Proje dosyası bulunamadı: {path}"
PROJECTIO_VERSION_UNSUPPORTED = (
    "Desteklenmeyen proje sürümü: {version} (beklenen: {expected})"
)

# Log seviyeleri
LOG_INFO = "[BİLGİ]"
LOG_WARNING = "[UYARI]"
LOG_ERROR = "[HATA]"
LOG_DEBUG = "[DEBUG]"
LOG_CLEAR = "Temizle"

# Log mesajları
LOG_APP_STARTED = "{title} başlatıldı."
LOG_REGISTERED_BLOCK_COUNT = "Kayıtlı blok sayısı: {count}"
LOG_GRAPH_LOADED = "Yeni proje yüklendi."
LOG_PROJECT_CREATED = "Yeni proje oluşturuldu."
LOG_PROJECT_LOADED = "Proje yüklendi: {path}"
LOG_PROJECT_SAVED = "Proje kaydedildi: {path}"
LOG_TARGET_CONFIRMED = (
    "[TESPİT] Hedef #{target_id} doğrulandı: "
    "{freq_mhz:.3f} MHz | Güç: {power:.1f} dB | SNR: {snr:.1f} dB"
)
LOG_UNKNOWN_NODE_TYPE = "Bilinmeyen blok tipi: {node_type_id}"
LOG_NODE_ADDED = "Blok eklendi: {name}"
LOG_NODE_CONFIG_UPDATED = "Blok ayarları güncellendi."
LOG_PIPELINE_STARTED = "Veri işleme hattı başlatıldı."
LOG_PIPELINE_STOPPED = "Veri işleme hattı durduruldu."
LOG_WORKSPACE_RESET = "Çalışma alanı sıfırlandı."
LOG_PLUGIN_DISCOVERY_SUMMARY = (
    "Eklenti taraması: {loaded} yüklendi, {failed} hata, {count} aday"
)
LOG_PLUGIN_DISCOVERY_LOADED = "Eklenti yüklendi: {name} ({manifest_count} manifest)"
LOG_PLUGIN_DISCOVERY_ERROR = "Eklenti hatası [{name}]: {error}"
ERROR_SYSTEM_RUNTIME = "Sistem hatası oluştu."

# Sağ tık menüsü
CTX_DELETE = "Sil"
CTX_DUPLICATE = "Çoğalt"
CTX_PROPERTIES = "Özellikler"
CTX_DISCONNECT = "Bağlantıları Kes"
CTX_ADD_BLOCK = "Blok Ekle"
CTX_SELECT_ALL = "Tümünü seç"
CTX_RESET_VIEW = "Görünümü Sıfırla"
CTX_FIT_ALL = "Tümünü Sığdır"

# Yerleşim
LAYOUT_PRESET_DESIGN = "Tasarım Yerleşimi"
LAYOUT_PRESET_OPERATION = "Operasyon Yerleşimi"
LAYOUT_PRESET_ANALYSIS = "Analiz Yerleşimi"

# Inspector
INSPECTOR_TITLE = "İnceleyici"
INSPECTOR_APPLY = "Uygula"
INSPECTOR_CLOSE_TOOLTIP = "Paneli kapat"
INSPECTOR_DESCRIPTION_MISSING = "Açıklama bulunmuyor."
INSPECTOR_PORT_NONE = "Yok"
INSPECTOR_PORT_INPUTS = "Girişler: {value}"
INSPECTOR_PORT_OUTPUTS = "Çıkışlar: {value}"
INSPECTOR_RUNTIME_STATE = "Durum:"
INSPECTOR_RUNTIME_FRAMES = "İşlenen Kare:"
INSPECTOR_RUNTIME_DROPS = "Boş Kare:"
INSPECTOR_RUNTIME_LATENCY = "Son Gecikme:"
INSPECTOR_RUNTIME_AVG_LATENCY = "Ort. Gecikme:"
INSPECTOR_RUNTIME_LAST_SEEN = "Son Veri:"
INSPECTOR_RUNTIME_LAST_OUTPUT = "Son Çıkış:"
INSPECTOR_RUNTIME_PROBE_HISTORY = "Probe Geçmişi:"
INSPECTOR_RUNTIME_LAST_ERROR = "Son Hata:"
INSPECTOR_FILE_BROWSE = "Gözat..."
INSPECTOR_FILE_PICKER_TITLE = "Dosya Seç"
INSPECTOR_FILE_PICKER_FILTER = "Tüm Dosyalar (*)"
INSPECTOR_ELAPSED = "{age:.1f} sn önce"
INSPECTOR_STATE_IDLE = "Hazır"
INSPECTOR_STATE_RUNNING = "Çalışıyor"
INSPECTOR_STATE_WARNING = "Uyarı"
INSPECTOR_STATE_STALE = "Beklemede"
INSPECTOR_STATE_ERROR = "Hata"
INSPECTOR_TAB_PROPERTIES = "Özellikler"
INSPECTOR_TAB_DETAILS = "Blok Detayları"
INSPECTOR_LABEL_INPUTS = "Giriş Portları"
INSPECTOR_LABEL_OUTPUTS = "Çıkış Portları"
INSPECTOR_SELECT_HINT = "Özelliklerini düzenlemek için bir bloğa çift tıklayın."

# Events
EVENT_LEVEL_INFO = "Bilgi"
EVENT_LEVEL_WARNING = "Uyarı"
EVENT_LEVEL_ERROR = "Hata"
EVENT_LEVEL_SUCCESS = "Başarılı"
EVENT_LEVEL_DEBUG = "Debug"
EVENT_NONE = "Henüz olay yok."

# Summary
SUMMARY_PIPELINE = "Pipeline:"
SUMMARY_ISSUES = "Sorun:"
SUMMARY_ISSUE_BREAKDOWN = "Sorun Dağılımı:"
SUMMARY_ACTIVE_NODES = "Aktif Blok Sayısı:"
SUMMARY_AVG_LATENCY = "Ortalama Gecikme:"
SUMMARY_SLOWEST_NODE = "En Yavaş Modül:"
SUMMARY_SOURCE = "Veri Kaynağı:"
SUMMARY_UI_MODE = "Kullanım Modu:"
SUMMARY_LAYOUT = "Ekran Düzeni:"
SUMMARY_PLUGINS = "Eklenti Durumu:"
SUMMARY_EVENTS = "Kayıtlı Olay:"
SUMMARY_LAST_EVENT = "Son Olay:"
SUMMARY_CONFIRMED_TARGETS = "Tespit Edilen Hedef:"
SUMMARY_ACTIVE_TRACKS = "Takip Edilen İz:"
SUMMARY_LAST_TARGET = "Son Tespit:"
SUMMARY_EVENT_BREAKDOWN = "{count} olay / {level}"
SUMMARY_ISSUE_BREAKDOWN_TEXT = "{errors} hata / {warnings} uyarı"
SUMMARY_PIPELINE_RUNNING = "Çalışıyor"
SUMMARY_PIPELINE_IDLE = "Hazır"
SUMMARY_PIPELINE_ERROR = "Hata"
SUMMARY_SOURCE_NOT_SELECTED = "Dosya seçilmedi"
SUMMARY_SOURCE_LOOP = "Sürekli Döngü"
SUMMARY_SOURCE_SINGLE_PASS = "Tek Geçiş"
SUMMARY_SOURCE_LABEL = "{name} ({mode})"
SUMMARY_PLUGIN_NONE = "Dış eklenti bulunamadı"
SUMMARY_PLUGIN_STATUS = "{loaded}/{count} yüklü"
SUMMARY_PLUGIN_STATUS_WITH_ERRORS = "{loaded}/{count} yüklü, {failed} hata"

# Edge debug
EDGE_DEBUG_PREVIEW = "Bağlantı önizlemesi"
EDGE_DEBUG_SOURCE = "Kaynak: {value}"
EDGE_DEBUG_TARGET = "Hedef: {value}"
EDGE_DEBUG_STATE = "Durum: {value}"
EDGE_DEBUG_WAITING = "Veri bekleniyor"
EDGE_DEBUG_TYPE = "Tip: {value}"
EDGE_DEBUG_PAYLOAD = "Yük: {value}"
EDGE_DEBUG_FRESHNESS = "Tazelik: {value:.0f} ms"
